<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="itext" Version="9.5.0" />
    <PackageReference Include="iTextSharp" Version="5.5.13.5" />
    <PackageReference Include="ScottPlot" Version="5.1.57" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CSMSLSourceCode\Source Code\.NET\CSMSL_dotNetCore\CSMSL.csproj" />
  </ItemGroup>

</Project>