name: Build and Publish Release Assets

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: windows-latest

    env:
      Solution_Name: PTsliCR.slnx
      Project_Path: PTsliCR/PTsliCR.csproj

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup .NET 8
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore
      run: dotnet restore $env:Solution_Name

    - name: Build
      run: dotnet build $env:Solution_Name --configuration Release --no-restore

    - name: Publish
      run: dotnet publish $env:Project_Path `
           -c Release `
           -r win-x64 `
           --self-contained true `
           -p:PublishSingleFile=true `
           -o publish

    - name: Upload EXE to Release Assets
      uses: softprops/action-gh-release@v2
      with:
        files: publish/*.exe
