name: Build and Publish Release Assets

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: windows-latest

    env:
      Solution_Name: PTsliCR.slnx
      Project_Path: PTsliCR/PTsliCR.csproj

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - run: dotnet restore $env:Solution_Name

    - run: dotnet build $env:Solution_Name -c Release --no-restore

    - run: dotnet publish $env:Project_Path `
        -c Release `
        -r win-x64 `
        --self-contained true `
        -p:PublishSingleFile=true `
        -o publish

    - name: Upload assets to release
      uses: softprops/action-gh-release@v2
      with:
        files: publish/*
